### ISSUE TITLE
Any way to get the syntax checker to know about parse transforms?

### ISSUE THREAD

**Issue by ReuvenSwirsky** [yuce/erlang-vscode#2]
Thanks, Yuce, for a terrific plugin. It's been working flawlessly for me ever since I got disgusted with Atom and switched to Visual Studio Code.

Is there any way to get the syntax checker to know about parse transforms? If I wanted to add this functionality myself, is there anything I should know before I go off with some half-baked strategy?

Thanks.

**Comment by yuce** [comment]
Thanks a lot! I'm glad the plugin it is useful to you.

The syntax checker being used in this plugin is a very dumb Texmate based one (which uses regexes), so it can mostly tell whether some text conforms to Erlang syntax. I guess a new syntax checker could be written but enabling checking parse transforms is non-trivial (since I think the parse transform must be run with Erlang code in the edited file) . Are there any Erlang editors which can do that?

Btw, there is a WIP update to this plugin at https://github.com/yuce/vscode-erlang-next which can list and complete functions defined in a project using an Erlang language server (but it's pretty rough at the moment). It would be a useful example of doing a little more advanced things than the current plugin can do.

**Comment by ReuvenSwirsky** [comment]
Thanks for the nice answer, Yuce!

I had no idea it was so "simple!" I had assumed it was using the Erlang
Parser. Ha!

Anyway, it works nicely for me, and maybe I'll get inspired to help the
project along a little myself. I haven't written any extensions for VSCode
yet (and I'm not really a JavaScript programmer) so there will be some
starting inertia.

**Comment by yuce** [comment]
It should be possible to compile Erlang source files, capture the output and highlight errors. The problem is, there are a few Erlang build systems, and some projects just use plain makefiles. Maybe the support could be restricted to rebar, rebar3 and erlang.mk. Of course in that case, the problem becomes discovering the build system a project uses. E.g., it's not trivial to distinguish between rebar and rebar3: http://www.rebar3.org/v3/discuss/56bcf9ba911a9621004559b8
